[server]
host = "127.0.0.1"
port = 8080

[database]
url = "ws://127.0.0.1:8000"
namespace = "book_rec"
database = "main"

[jwt]
secret = "your-super-secret-jwt-key-change-in-production"
expiration_hours = 24

[cloudinary]
cloud_name = "your-cloud-name"
api_key = "your-api-key"
api_secret = "your-api-secret"
upload_preset = "book-covers"

[ml_model]
model_path = "./models/recommendation_model.pkl"
python_path = "./python_models"